### ISSUE TITLE
bug: refuses to load w3s.link content in browsers because it violates CSP 

### ISSUE THREAD

**Issue by akhileshthite** [web3-storage/w3link#44] opened 2023-02-04 20:07 UTC
Error:
![Screenshot 2023-02-05 at 12 41 25 AM](https://user-images.githubusercontent.com/68826419/216787558-61737e38-202b-4730-81fe-a054baf5fc31.png)

Everything works fine on `dweb.link` gateway.

**Comment by vasco-santos** [comment] 2023-02-06 15:50
Hey @akhileshthite 
This is not a bug, but a policy that we decided to move forward with in the gateway operated by web3.storage team. 
You can read more about this in https://blog.web3.storage/posts/badbits-and-goodbits-csp-in-w3link

Closing the issue, but feel free to re-open if you have further questions around this

**Closed by vasco-santos** 2023-02-06 15:50 UTC
Labels: kind/bug, need/triage

**Comment by akhileshthite** [comment] 2023-02-07 04:41
> Hey @akhileshthite 
> 
> This is not a bug, but a policy that we decided to move forward with in the gateway operated by web3.storage team. 
> 
> You can read more about this in https://blog.web3.storage/posts/badbits-and-goodbits-csp-in-w3link
> 
> 
> 
> Closing the issue, but feel free to re-open if you have further questions around this

Hey,
Thanks for sharing the information.
It's clear now.
